apiVersion: apps/v1
kind: Deployment
metadata:
  name: cricbuzz-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cricbuzz-api
  template:
    metadata:
      labels:
        app: cricbuzz-api
    spec:
      containers:
      - name: api
        image: cricbuzz-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DATABASE_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: JWT_SECRET_KEY
        - name: DB_POOL_SIZE
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: DB_POOL_SIZE
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 15
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
