apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: supersecretpassword
  DATABASE_URL: "postgresql://postgres:supersecretpassword@postgres-service:5432/cricbuzz"
  JWT_SECRET_KEY: "change-me-to-a-random-64-char-string-before-deploying-to-production"
